Feature: DockerfileとCDの追加
acrylic-style/RemindBot pull request #1
Opened 2023-09-25 09:37 UTC by testusuke

# 実装内容

- Dockerfileの追加
- CDの追加

# レビュー観点

- 美しいか

2023-09-25 15:13 UTC, testusuke commented
@acrylic-style reviewerに追加し忘れた（ ;  ; ）

2023-09-25 16:21 UTC, acrylic-style requested changes
ファイルの最後の改行欲しいかもー

2023-09-25 22:25 UTC, testusuke commented
たし🦀

2023-09-28 04:06 UTC, testusuke commented
> ファイルの最後の改行欲しいかもー
@acrylic-style 追加した！

2023-09-28 09:36 UTC, merged